name: "MineWaypoints"
author: "Syr0ws"
version: "1.0.0"
main: com.github.syr0ws.minewaypoints.MineWaypoints
api-version: 1.17
libraries:
  - org.xerial:sqlite-jdbc:3.47.1.0
  - org.postgresql:postgresql:42.7.4
  - com.mysql:mysql-connector-j:9.1.0
  - com.zaxxer:HikariCP:6.2.1
  - org.mybatis:mybatis:3.5.7
commands:
  waypoints:
    description: "Open the waypoints menu."
    aliases: ["waypoint", "wp"]