name: "MineWaypoints"
author: "Syr0ws"
version: "1.0.0"
main: com.github.syr0ws.minewaypoints.MineWaypoints
api-version: 1.17
commands:
  waypoints:
    description: "Open the waypoints menu."
    aliases: ["waypoint", "wp"]